### ISSUE TITLE
Missing Report VFR

### ISSUE THREAD

**Issue by Iwhite67** [vaccfr/France-Controller-Pack#6]
I report here Missing Report point VFR

LFKC : NW, PB

**Comment by Iwhite67** [comment]
LFMT : Missing SA (Ne fait pas partie de LFMT mais de la fir LFMM) , Double point de report sur ER (gauche de AM, 43° 34’ 43”N - 004° 06’ 03”E)

**Comment by pierr3** [comment]
Fixed in dev
